cc_library(
    name = 'syntax_tree',
    srcs = [
        'class_node.cpp',
        'data_type.cpp',
        'print_node.cpp',
        'ctrl_node.cpp',
        'declare_node.cpp',
        'syntax_tree.cpp',
        'func_node.cpp',
        'exp_node.cpp',
    ],
)
