#cc_library(
#  name = 'syntax_tree',
#  srcs = [
#    'syntax_tree.cpp',
#       'class_node.cpp',
#       'data_type.cpp',
#       'print_node.cpp',
#       'ctrl_node.cpp',
#       'declare_node.cpp',
#       'func_node.cpp',
#       'exp_node.cpp',
#   ],
#  deps = [
#    ':program_node',
#  ]
#)

cc_library(
  name = 'program_node',
  srcs = [
    'program_node.cpp',
  ],
)
